### ISSUE TITLE
ToDo おもいつくもの 1602229

### ISSUE THREAD

**Issue by kassailattice628** [kassailattice628/PTB_MacTest#1]
## 概要
この Issue はPTB_MacTest への実装タスクの一覧です．
 
## 変更点
- [x] Ver10.2 への対応（参考https://github.com/kassailattice628/NBA_Rec_ver10_2)
  - [x] GUI window の変更
  - [x] 刺激の追加, NBA本体，main_loop
  - [x] Rec_ver10_2 (forTokuoka) でいれた DIO ２種への対応

## To Do
- [ ] 刺激と DO output タイミング（外部トリガ）をくみやすくするために，スクリプトの分散
- [ ] 刺激種類を増やす
  - [ ] ランダムドット for reverse correlation
    - [ ] シードの保存，変数を .mat ファイルとして保存？
  - [ ] ムービングバー
  - [ ] ルーミング

### 備考
上記とあわせて，Ver10.3 へ
分散した関数を １つのファイルにまとめた方がいい？
